version: '3'

services:
  haproxy:
    image: haproxy:latest
    volumes:
      - ./haproxy/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg
    ports:
      - "3000:80"
    networks:
      - network-venta-de-pasajes
    depends_on:
      - search-service
      - baggage-service

  search-service:
    build:
      context: .
      dockerfile: ./cmd/search-service/Dockerfile
    ports:
      - "8080"
    environment:
      - MONGO_URL=mongodb://mongodb:27017
    networks:
      - network-venta-de-pasajes

  baggage-service:
    build:
      context: .
      dockerfile: ./cmd/baggage-service/Dockerfile
    ports:
      - "8081"
    environment:
      - MONGO_URL=mongodb://mongodb:27017
    networks:
      - network-venta-de-pasajes

  mongodb:
    image: mongo
    volumes:
      - ~/Sites/Data/mongodb-data:/data/db
    ports:
      - "27017:27017"
    networks:
      - network-venta-de-pasajes

networks:
  network-venta-de-pasajes:
    driver: bridge
